---
abstract: Perl interface to the MegaHAL natural language conversation simulator.
author:
  - 'Alexandr Ciornii <alexchorny@gmail.com>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AI-MegaHAL
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  repository: http://github.com/chorny/AI-MegaHAL
  x_Keywords:
    - megahal
    - chat
version: 0.07_01
