--- #YAML:1.0
name:                AI-MegaHAL
version:             0.07
abstract:            Perl interface to the MegaHAL natural language conversation simulator.
license:             gpl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Alexandr Ciornii <alexchorny@gmail.com>
